### ISSUE TITLE
[Windows 10 21H1] I could not complete the compilation by README.md

### ISSUE THREAD

**Issue by hu3rror** [bytanuky/dumb-browser#2]
Hi, I ran into some trouble.

OS: Windows 10 21H1
Powershell: 7.1.4
Python: 3.9.6
Visual Studio 2019 and Windows 10 SDK 10.0.19041+ had been installed.

`python ./scripts/prepare.py` and `python ./scripts/sync.py` are OK.

But run `python ./scripts/build.py release` shows such error:
```
PS C:\Users\xxx\git\dumb-browser> python ./scripts/build.py release
$ gn gen out\Release
ERROR at //build/toolchain/gcc_toolchain.gni:41:3: Assertion failed.

  assert(symbol_level >= 1,

  ^-----

enable_resource_allowlist_generation=true requires symbol_level >= 1

See //chrome/browser/buildflags.gni:7:1: whence it was imported.

import("//build/toolchain/gcc_toolchain.gni")

^-------------------------------------------

See //BUILD.gn:19:1: whence it was imported.

import("//chrome/browser/buildflags.gni")

^---------------------------------------







$ autoninja -C out\Release chrome
"C:\Users\xxx\git\dumb-browser\depot_tools\ninja.exe" -C out\Release chrome -j 10

ninja: Entering directory `out\Release'

Traceback (most recent call last):
  File "C:\Users\xxx\git\dumb-browser\scripts\build.py", line 130, in <module>
    sys.exit(main(sys.argv[1:]))
  File "C:\Users\xxx\git\dumb-browser\scripts\build.py", line 126, in main
    return run_command(['autoninja', '-C', path_for_gn, 'chrome'], cwd=CHROMIUM_SRC_DIR)
  File "C:\Users\xxx\git\dumb-browser\scripts\utils.py", line 110, in run_command
    print(output.decode(sys.stdout.encoding))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 41: invalid continuation byte
```

How can I solve this problem?

Thank you.

**Comment by f32y** [comment]
Sorry for this. I did not test on Windows in recent versions. This will be fixed within this week.
